sample1:
  cell: "nB"            # Name of the cell type or tissue
  condition: "WT1"         # Experimental condition
  reps: [1]              # List of replicate numbers
  fasta_path: "/home/bsc/bsc008978/test_data/"
  genome: "/gpfs/scratch/bsc08/bsc008978/db/Genomes/Homo_sapiens-GRCh38.p13/Homo_sapiens-GRCh38.p13.fa" # Reference genome for alignment
  trimming: "trimgalore"       # Trimming method, e.g., 'trimgalore', 'adapterremoval', 'noTrimming'
  time_per_job: "2:00:00"
  cpus_per_job: 10
  output_dir: "/home/bsc/bsc008978/Box/pipelines/RNAseq_SF/"  # could override command line outdir


sample2:
  cell: "CellTypeB"
  condition: "Treatment"
  reps: [1, 2]
  genome: "/path/to/genomeB.fa"
  trimming: "noTrimming"
  time_per_job: "2:00:00"
  cpus_per_job: 10
  output_dir: "/home/user/Pipelines/RNAseq_SF/results"  # could override command line outdir



