sample1:
  cell: "nB"            
  condition: "WT1"         
  reps: [1]              
  fasta_path: "/home/bsc/bsc008978/test_data/"
  trimming: "trimgalore"
  STAR_index_dir: "/gpfs/projects/bsc08/shared_projects/IJC_3Dchromatin/genomes/human/GRCh38/current/indices/STAR/" 
  gtf_annotation: "/gpfs/projects/bsc08/shared_projects/IJC_3Dchromatin/genomes/human/GRCh38/current/Homo_sapiens.GRCh38.104.gtf"



